### ISSUE TITLE
Add "get likeliest" methods to Player Loader

### ISSUE THREAD

**Issue by jaxmann** [jaxmann/fifa-sbc-squad-solver#9]
methods like 20 best value at position
20 cheapest 87's
100 best coins/rating players

cache helper lists (like 85+) for faster calcs)

**Comment by cnbrkc** [comment]
How can we install and use your application?

**Comment by jaxmann** [comment]
@cnbrkc it's still a work in progress right now

**Comment by cnbrkc** [comment]
thanks I hope you make it available!

**Comment by jaxmann** [comment]
np, i will. I'll post a better readme on the main page once it's usable too
